version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    env_file:
      - ./backend/.env.production  # Secure file with real secrets
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production  # Use real values on EC2 only
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
