version: "3.8"

services:
  backend-1:
    build: ./backend
    container_name: backend-1
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.production
    networks:
      - app-network

  backend-2:
    build: ./backend
    container_name: backend-2
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env.production
    networks:
      - app-network

  backend-3:
    build: ./backend
    container_name: backend-3
    ports:
      - "3003:3003"
    env_file:
      - ./backend/.env.production
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
      - backend-3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
